### ISSUE TITLE
Please add vswhere to scoop

### ISSUE THREAD

**Issue by dariusdamalakas** [Microsoft/vswhere#122]
Choco seems to require elevated privileges to install `vswere`. That does not look right.    May i suggest that `vswhere` gets added to [scoop](http://scoop.sh)?   

P.s. here's the full output from running `choco install vswhere`:
````
PS C:\Users\ddamalakas> choco install vswhere
Chocolatey v0.10.7
Chocolatey detected you are not running from an elevated command shell
 (cmd/powershell).

 You may experience errors - many functions/packages
 require admin rights. Only advanced users should run choco w/out an
 elevated shell. When you open the command shell, you should ensure
 that you do so with "Run as Administrator" selected. If you are
 attempting to use Chocolatey in a non-administrator setting, you
 must select a different location other than the default install
 location. See
 https://chocolatey.org/install#non-administrative-install for details.


 Do you want to continue?([Y]es/[N]o): y

Installing the following packages:
vswhere
By installing you accept licenses for the packages.
Progress: Downloading vswhere 2.2.11... 100%
vswhere not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\vswhere\build' is denied.
vswhere package files install completed. Performing other installation steps.
The install of vswhere was NOT successful.
vswhere not installed. An error occurred during installation:
 Access to the path 'C:\ProgramData\chocolatey\lib\vswhere\build' is denied.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\lib-bad' is denied.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Access to the path 'C:\ProgramData\chocolatey\lib-bad' is denied.
Maximum tries of 3 reached. Throwing error.
Cannot create directory "C:\ProgramData\chocolatey\lib-bad". Error was:
System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\lib-bad' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHos
)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.<>c__DisplayClass64.<create_directory>b__63() in c:\codeloc
l\chocolatey2\src\chocolatey\infrastructure\filesystem\DotNetFileSystem.cs:line 640
   at chocolatey.infrastructure.tolerance.FaultTolerance.<>c__DisplayClass1.<retry>b__0() in c:\codelocal\chocolatey2\s
c\chocolatey\infrastructure\tolerance\FaultTolerance.cs:line 61
   at chocolatey.infrastructure.tolerance.FaultTolerance.retry[T](Int32 numberOfTries, Func`1 function, Int32 waitDurat
onMilliseconds, Int32 increaseRetryByMilliseconds, Boolean isSilent) in c:\codelocal\chocolatey2\src\chocolatey\infrast
ucture\tolerance\FaultTolerance.cs:line 104
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory(String directoryPath) in c:\codelocal\choc
latey2\src\chocolatey\infrastructure\filesystem\DotNetFileSystem.cs:line 647
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.create_directory_if_not_exists(String directoryPath, Boolea
 ignoreError) in c:\codelocal\chocolatey2\src\chocolatey\infrastructure\filesystem\DotNetFileSystem.cs:line 718
Access to the path 'C:\ProgramData\chocolatey\lib-bad' is denied.
````

**Comment by heaths** [comment]
Please see https://github.com/chocolatey/choco/wiki/Installation for instructions for installing chocolatey and/or packages without elevated privileges.

Given we now include _vswhere_ with the Visual Studio Installer itself, we'll not be adding it to any further package managers. It's also available on nuget and released on GitHub making it already very accessible should you not simply detect if it's already installed with VS.

**Comment by dariusdamalakas** [comment]
Not everyone is running latest VisualStudio, I understand that `vswhere` is only installed with VS2017 or later. So that is not a viable option to rely on.  

Good to header that this is in nuget as well, this can be scripted easily, so that will work. Thanks.

**Comment by heaths** [comment]
_vswhere_ also didn't originally handle older versions of Visual Studio and having added support only complicated scenarios we intended to support.

**Comment by heaths** [comment]
Given scoop's rise in popularity, I went ahead and implemented this. It's now in the main bucket: https://github.com/ScoopInstaller/Main/blob/master/bucket/vswhere.json
